#pragma once
constexpr const float M_PI = 3.14159265358979323846f;
#define HITGROUP_GENERIC	  0
#define HITGROUP_HEAD         1
#define HITGROUP_CHEST        2
#define HITGROUP_STOMACH      3
#define HITGROUP_LEFTARM      4    
#define HITGROUP_RIGHTARM     5
#define HITGROUP_LEFTLEG      6
#define HITGROUP_RIGHTLEG     7
#define HITGROUP_GEAR         10
enum FlowType_t
{
	FLOW_OUTGOING = 0,
	FLOW_INCOMING = 1,
	FLOW_MAX = 2
};
enum Typetype_t
{
	TYPE_GENERIC = 0,
	TYPE_LOCALPLAYER = 1
};
enum ClassId
{
    ClassId_CAI_BaseNPC = 0,
    ClassId_CAK47,
    ClassId_CBaseAnimating,
    ClassId_CBaseAnimatingOverlay,
    ClassId_CBaseAttributableItem,
    ClassId_CBaseButton,
    ClassId_CBaseCombatCharacter,
    ClassId_CBaseCombatWeapon,
    ClassId_CBaseCSGrenade,
    ClassId_CBaseCSGrenadeProjectile,
    ClassId_CBaseDoor,
    ClassId_CBaseEntity,
    ClassId_CBaseFlex,
    ClassId_CBaseGrenade,
    ClassId_CBaseParticleEntity,
    ClassId_CBasePlayer,
    ClassId_CBasePropDoor,
    ClassId_CBaseTeamObjectiveResource,
    ClassId_CBaseTempEntity,
    ClassId_CBaseToggle,
    ClassId_CBaseTrigger,
    ClassId_CBaseViewModel,
    ClassId_CBaseVPhysicsTrigger,
    ClassId_CBaseWeaponWorldModel,
    ClassId_CBeam,
    ClassId_CBeamSpotlight,
    ClassId_CBoneFollower,
    ClassId_CBreakableProp,
    ClassId_CBreakableSurface,
    ClassId_CC4,
    ClassId_CCascadeLight,
    ClassId_CChicken,
    ClassId_CColorCorrection,
    ClassId_CColorCorrectionVolume,
    ClassId_CCSGameRulesProxy,
    ClassId_CCSPlayer,
    ClassId_CCSPlayerResource,
    ClassId_CCSRagdoll,
    ClassId_CCSTeam,
    ClassId_CDEagle,
    ClassId_CDecoyGrenade,
    ClassId_CDecoyProjectile,
    ClassId_CDynamicLight,
    ClassId_CDynamicProp,
    ClassId_CEconEntity,
    ClassId_CEconWearable,
    ClassId_CEmbers,
    ClassId_CEntityDissolve,
    ClassId_CEntityFlame,
    ClassId_CEntityFreezing,
    ClassId_CEntityParticleTrail,
    ClassId_CEnvAmbientLight,
    ClassId_CEnvDetailController,
    ClassId_CEnvDOFController,
    ClassId_CEnvParticleScript,
    ClassId_CEnvProjectedTexture,
    ClassId_CEnvQuadraticBeam,
    ClassId_CEnvScreenEffect,
    ClassId_CEnvScreenOverlay,
    ClassId_CEnvTonemapController,
    ClassId_CEnvWind,
    ClassId_CFEPlayerDecal,
    ClassId_CFireCrackerBlast,
    ClassId_CFireSmoke,
    ClassId_CFireTrail,
    ClassId_CFish,
    ClassId_CFlashbang,
    ClassId_CFogController,
    ClassId_CFootstepControl,
    ClassId_CFunc_Dust,
    ClassId_CFunc_LOD,
    ClassId_CFuncAreaPortalWindow,
    ClassId_CFuncBrush,
    ClassId_CFuncConveyor,
    ClassId_CFuncLadder,
    ClassId_CFuncMonitor,
    ClassId_CFuncMoveLinear,
    ClassId_CFuncOccluder,
    ClassId_CFuncReflectiveGlass,
    ClassId_CFuncRotating,
    ClassId_CFuncSmokeVolume,
    ClassId_CFuncTrackTrain,
    ClassId_CGameRulesProxy,
    ClassId_CHandleTest,
    ClassId_CHEGrenade,
    ClassId_CHostage,
    ClassId_CHostageCarriableProp,
    ClassId_CIncendiaryGrenade,
    ClassId_CInferno,
    ClassId_CInfoLadderDismount,
    ClassId_CInfoOverlayAccessor,
    ClassId_CItem_Healthshot,
    ClassID_CItemDogTags,
    ClassId_CKnife,
    ClassId_CKnifeGG,
    ClassId_CLightGlow,
    ClassId_CMaterialModifyControl,
    ClassId_CMolotovGrenade,
    ClassId_CMolotovProjectile,
    ClassId_CMovieDisplay,
    ClassId_CParticleFire,
    ClassId_CParticlePerformanceMonitor,
    ClassId_CParticleSystem,
    ClassId_CPhysBox,
    ClassId_CPhysBoxMultiplayer,
    ClassId_CPhysicsProp,
    ClassId_CPhysicsPropMultiplayer,
    ClassId_CPhysMagnet,
    ClassId_CPlantedC4,
    ClassId_CPlasma,
    ClassId_CPlayerResource,
    ClassId_CPointCamera,
    ClassId_CPointCommentaryNode,
    ClassId_CPointWorldText,
    ClassId_CPoseController,
    ClassId_CPostProcessController,
    ClassId_CPrecipitation,
    ClassId_CPrecipitationBlocker,
    ClassId_CPredictedViewModel,
    ClassId_CProp_Hallucination,
    ClassId_CPropDoorRotating,
    ClassId_CPropJeep,
    ClassId_CPropVehicleDriveable,
    ClassId_CRagdollManager,
    ClassId_CRagdollProp,
    ClassId_CRagdollPropAttached,
    ClassId_CRopeKeyframe,
    ClassId_CSCAR17,
    ClassId_CSceneEntity,
    ClassId_CSensorGrenade,
    ClassId_CSensorGrenadeProjectile,
    ClassId_CShadowControl,
    ClassId_CSlideshowDisplay,
    ClassId_CSmokeGrenade,
    ClassId_CSmokeGrenadeProjectile,
    ClassId_CSmokeStack,
    ClassId_CSpatialEntity,
    ClassId_CSpotlightEnd,
    ClassId_CSprite,
    ClassId_CSpriteOriented,
    ClassId_CSpriteTrail,
    ClassId_CStatueProp,
    ClassId_CSteamJet,
    ClassId_CSun,
    ClassId_CSunlightShadowControl,
    ClassId_CTeam,
    ClassId_CTeamplayRoundBasedRulesProxy,
    ClassId_CTEArmorRicochet,
    ClassId_CTEBaseBeam,
    ClassId_CTEBeamEntPoint,
    ClassId_CTEBeamEnts,
    ClassId_CTEBeamFollow,
    ClassId_CTEBeamLaser,
    ClassId_CTEBeamPoints,
    ClassId_CTEBeamRing,
    ClassId_CTEBeamRingPoint,
    ClassId_CTEBeamSpline,
    ClassId_CTEBloodSprite,
    ClassId_CTEBloodStream,
    ClassId_CTEBreakModel,
    ClassId_CTEBSPDecal,
    ClassId_CTEBubbles,
    ClassId_CTEBubbleTrail,
    ClassId_CTEClientProjectile,
    ClassId_CTEDecal,
    ClassId_CTEDust,
    ClassId_CTEDynamicLight,
    ClassId_CTEEffectDispatch,
    ClassId_CTEEnergySplash,
    ClassId_CTEExplosion,
    ClassId_CTEFireBullets,
    ClassId_CTEFizz,
    ClassId_CTEFootprintDecal,
    ClassId_CTEFoundryHelpers,
    ClassId_CTEGaussExplosion,
    ClassId_CTEGlowSprite,
    ClassId_CTEImpact,
    ClassId_CTEKillPlayerAttachments,
    ClassId_CTELargeFunnel,
    ClassId_CTEMetalSparks,
    ClassId_CTEMuzzleFlash,
    ClassId_CTEParticleSystem,
    ClassId_CTEPhysicsProp,
    ClassId_CTEPlantBomb,
    ClassId_CTEPlayerAnimEvent,
    ClassId_CTEPlayerDecal,
    ClassId_CTEProjectedDecal,
    ClassId_CTERadioIcon,
    ClassId_CTEShatterSurface,
    ClassId_CTEShowLine,
    ClassId_CTesla,
    ClassId_CTESmoke,
    ClassId_CTESparks,
    ClassId_CTESprite,
    ClassId_CTESpriteSpray,
    ClassId_CTest_ProxyToggle_Networkable,
    ClassId_CTestTraceline,
    ClassId_CTEWorldDecal,
    ClassId_CTriggerPlayerMovement,
    ClassId_CTriggerSoundOperator,
    ClassId_CVGuiScreen,
    ClassId_CVoteController,
    ClassId_CWaterBullet,
    ClassId_CWaterLODControl,
    ClassId_CWeaponAug,
    ClassId_CWeaponAWP,
    ClassId_CWeaponBaseItem,
    ClassId_CWeaponBizon,
    ClassId_CWeaponCSBase,
    ClassId_CWeaponCSBaseGun,
    ClassId_CWeaponCycler,
    ClassId_CWeaponElite,
    ClassId_CWeaponFamas,
    ClassId_CWeaponFiveSeven,
    ClassId_CWeaponG3SG1,
    ClassId_CWeaponGalil,
    ClassId_CWeaponGalilAR,
    ClassId_CWeaponGlock,
    ClassId_CWeaponHKP2000,
    ClassId_CWeaponM249,
    ClassId_CWeaponM3,
    ClassId_CWeaponM4A1,
    ClassId_CWeaponMAC10,
    ClassId_CWeaponMag7,
    ClassId_CWeaponMP5Navy,
    ClassId_CWeaponMP7,
    ClassId_CWeaponMP9,
    ClassId_CWeaponNegev,
    ClassId_CWeaponNOVA,
    ClassId_CWeaponP228,
    ClassId_CWeaponP250,
    ClassId_CWeaponP90,
    ClassId_CWeaponSawedoff,
    ClassId_CWeaponSCAR20,
    ClassId_CWeaponScout,
    ClassId_CWeaponSG550,
    ClassId_CWeaponSG552,
    ClassId_CWeaponSG556,
    ClassId_CWeaponSSG08,
    ClassId_CWeaponTaser,
    ClassId_CWeaponTec9,
    ClassId_CWeaponTMP,
    ClassId_CWeaponUMP45,
    ClassId_CWeaponUSP,
    ClassId_CWeaponXM1014,
    ClassId_CWorld,
    ClassId_DustTrail,
    ClassId_MovieExplosion,
    ClassId_ParticleSmokeGrenade,
    ClassId_RocketTrail,
    ClassId_SmokeTrail,
    ClassId_SporeExplosion,
    ClassId_SporeTrail,
    MAX_CLASSID
};
enum EntityFlags
{
	FL_ONGROUND = (1 << 0),
	FL_DUCKING = (1 << 1),
	FL_WATERJUMP = (1 << 2),
	FL_ONTRAIN = (1 << 3),
	FL_INRAIN = (1 << 4),
	FL_FROZEN = (1 << 5),
	FL_ATCONTROLS = (1 << 6),
	FL_CLIENT = (1 << 7),
	FL_FAKECLIENT = (1 << 8),
	MAX_ENTITYFLAGS
};
enum FontRenderFlag_t
{
	FONT_LEFT = 0,
	FONT_RIGHT = 1,
	FONT_CENTER = 2
};
enum ItemDefinitionIndex
{
	WEAPON_DEAGLE = 1,
	WEAPON_ELITE = 2,
	WEAPON_FIVESEVEN = 3,
	WEAPON_GLOCK = 4,
	WEAPON_AK47 = 7,
	WEAPON_AUG = 8,
	WEAPON_AWP = 9,
	WEAPON_FAMAS = 10,
	WEAPON_G3SG1 = 11,
	WEAPON_GALILAR = 13,
	WEAPON_M249 = 14,
	WEAPON_M4A1 = 16,
	WEAPON_MAC10 = 17,
	WEAPON_P90 = 19,
	WEAPON_UMP45 = 24,
	WEAPON_XM1014 = 25,
	WEAPON_BIZON = 26,
	WEAPON_MAG7 = 27,
	WEAPON_NEGEV = 28,
	WEAPON_SAWEDOFF = 29,
	WEAPON_TEC9 = 30,
	WEAPON_TASER = 31,
	WEAPON_HKP2000 = 32,
	WEAPON_MP7 = 33,
	WEAPON_MP9 = 34,
	WEAPON_NOVA = 35,
	WEAPON_P250 = 36,
	WEAPON_SCAR20 = 38,
	WEAPON_SG556 = 39,
	WEAPON_SSG08 = 40,
	WEAPON_KNIFE_CT = 42,
	WEAPON_FLASHBANG = 43,
	WEAPON_HEGRENADE = 44,
	WEAPON_SMOKEGRENADE = 45,
	WEAPON_MOLOTOV = 46,
	WEAPON_DECOY = 47,
	WEAPON_INCGRENADE = 48,
	WEAPON_C4 = 49,
	WEAPON_KNIFE_T = 59,
	WEAPON_M4A1_SILENCER = 60,
	WEAPON_USP_SILENCER = 61,
	WEAPON_CZ75A = 63,
	WEAPON_REVOLVER = 64,
	WEAPON_KNIFE_BAYONET = 500,
	WEAPON_KNIFE_FLIP = 505,
	WEAPON_KNIFE_GUT = 506,
	WEAPON_KNIFE_KARAMBIT = 507,
	WEAPON_KNIFE_M9_BAYONET = 508,
	WEAPON_KNIFE_TACTICAL = 509,
	WEAPON_KNIFE_FALCHION = 512,
	WEAPON_KNIFE_BOWIE = 514,
	WEAPON_KNIFE_BUTTERFLY = 515,
	WEAPON_KNIFE_PUSH = 516
};

enum movetype_t
{
	MOVETYPE_NONE = 0,	// never moves
	MOVETYPE_ISOMETRIC,			// For players -- in TF2 commander view, etc.
	MOVETYPE_WALK,				// Player only - moving on the ground
	MOVETYPE_STEP,				// gravity, special edge handling -- monsters use this
	MOVETYPE_FLY,				// No gravity, but still collides with stuff
	MOVETYPE_FLYGRAVITY,		// flies through the air + is affected by gravity
	MOVETYPE_VPHYSICS,			// uses VPHYSICS for simulation
	MOVETYPE_PUSH,				// no clip to world, push and crush
	MOVETYPE_NOCLIP,			// No gravity, no collisions, still do velocity/avelocity
	MOVETYPE_LADDER,			// Used by players only when going onto a ladder
	MOVETYPE_OBSERVER,			// Observer movement, depends on player's observer mode
	MOVETYPE_CUSTOM,			// Allows the entity to describe its own physics
	MOVETYPE_LAST = MOVETYPE_CUSTOM,
	MOVETYPE_MAX_BITS = 4
};